### PR TITLE
Fixed the issues with starting the app

### PR DESCRIPTION
**Pull request by jerichokeyne**
I got the code to open up the ui. I have not tested whether any of the buttons function or not though.

### CODE REVIEW

**Comment by jerichokeyne** [comment]
Fixed an issue with finding a roku on the local network. Still not sure if any of the roku buttons are working yet, but the about dialog now works

**Comment by jerichokeyne** [comment]
I also noticed that the find function assumes that there's only one roku on your network. So that'll eventually have to be changed to support selecting a roku

**Comment by jerichokeyne** [comment]
I noticed that the scaling didn't quite work on the Pinephone's small screen, so I adjusted the default size so it works correctly (in both portrait and landscape). I also got a chance to test it on my Pinephone to control my Roku soundbar, and all the buttons seem to work just fine. I also noticed that my desktop finds my Roku just fine with the ssdp method, but my Pinephone doesn't and has to fallback to the slower find function. Not too sure why though

**Comment by 1peter10** [comment]
Amazing work! Thank you very much!

**Pull request merged**
